### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by justinwoo**
btw, this branch name should be `compiler/0.12`, not with the leading pound

### CODE REVIEW

**Comment by justinwoo** [comment]
@Thimoteus could you merge and release? I need this for some upstream packages/pipes/spec

**Comment by Thimoteus** [comment]
@justinwoo what else is needed besides the merge?

**Comment by justinwoo** [comment]
@Thimoteus just a new major release. Thanks!

**Comment by Thimoteus** [comment]
@justinwoo ok that should do it

**Pull request merged**
